# https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules
name: 'Update KernelSU'

on:
  schedule:
    - cron:  '0 13 * * *'
  # 推送到 thirteen 分支时主动执行
  push:
    branches: [thirteen]
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update KernelSU
      run: |
        rm -rf ./drivers/kernelsu
        git clone https://github.com/tiann/KernelSU
        cp -rf ./KernelSU/kernel ./drivers/kernelsu
        rm -rf KernelSU

    - name: Commit update
      run: |
        git config --global user.name 'KernelSU'
        git config --global user.email 'twsxtd@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -a --amend --no-edit && git push || echo "No changes to commit!"